name: DiscordBridge
version: @version@
main: github.m5rian.DiscordBridge
authors: [Marian]
api-version: 1.16
description: A integration for Discord and Minecraft

commands:
  verify:
    description: Confirm your verfification