name: DiscordMinecraftIntegration
version: '${version}'
main: com.github.m5rian.discordMinecraftIntegration.DiscordBridge
authors: [Marian]
api-version: 1.18
description: A integration for Discord and Minecraft

commands:
  verify:
    description: Confirm your verfification
    usage: /<command>